package cmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"

	"github.com/AlecAivazis/survey/v2"
	"github.com/dolmen-go/codegen"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"

	"github.com/KarolosLykos/advent-of-code-gen/internal/config"
)

const mainTemplate = `// Code generated by aocgen; DO NOT EDIT.
package main

import (
	"fmt"
)

func main() {
	fmt.Println("aoc initialized")
}`

func NewInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize AoC",
		Long:  "Initialize a new AoC project.",
		RunE:  initCmd,
	}

	return cmd
}

func initCmd(_ *cobra.Command, _ []string) error {
	cfg, err := config.GetUserConfig()
	if err != nil {
		return err
	}

	if err = initializeConfig(cfg); err != nil {
		return err
	}

	if err = config.UpdateUserConfig(cfg); err != nil {
		return err
	}

	if _, err := os.Stat(cfg.ProjectDir + "/go.mod"); err == nil && !errors.Is(err, os.ErrNotExist) {
		logrus.Infof("already initialized")

		return nil
	}

	if err := os.Mkdir(cfg.ProjectDir, 0750); err != nil && !errors.Is(err, os.ErrExist) {
		logrus.Errorf("error creating directory: %v", err)

		return err
	}

	if err := goModInit(cfg.ProjectDir, cfg.Module); err != nil {
		logrus.Errorf("initializing module: %v", err)

		return err
	}

	if _, err := os.Stat(cfg.ProjectDir + "/main.go"); err == nil && !errors.Is(err, os.ErrNotExist) {
		logrus.Infof("mod file already exists")
	}

	tmpl := codegen.MustParse(mainTemplate)
	if err := tmpl.CreateFile(cfg.ProjectDir+"/main.go", nil); err != nil {
		logrus.Fatal(err)
	}

	logrus.Infof("Created main file: %s", "main.go")

	return nil
}

func initializeConfig(cfg *config.Config) error {
	if cfg.ProjectDir != "" && cfg.Module != "" {
		return nil
	}

	qs := []*survey.Question{
		{
			Name:     "projectDir",
			Prompt:   &survey.Input{Message: "Enter your project directory ($HOME/path/to/directory:"},
			Validate: survey.Required,
		},
		{
			Name:     "module",
			Prompt:   &survey.Input{Message: "Enter your module path (example.com/example):"},
			Validate: survey.Required,
		},
		// {
		// 	Name:     "session",
		// 	Prompt:   &survey.Input{Message: "Enter session cookie from AoC website"},
		// 	Validate: survey.Required,
		// },
	}

	return survey.Ask(qs, cfg)
}

func goModInit(projectPath, m string) error {
	if err := cdToProject(projectPath); err != nil {
		logrus.Errorf("could not chnage directory: %v", err)

		return err
	}

	cmd := exec.Command("go", "mod", "init", m)

	return cmd.Run()
}

func cdToProject(projectName string) error {
	return os.Chdir(fmt.Sprintf("%s", projectName))
}
