package templates

const SolutionTemplate = `// Code generated by aoc; DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"
)

func main() {
	start := time.Now()
	fmt.Println("Year: {{.Year}}| Day: {{.Day}}")
	input, err := parseInput("input.txt")
	if err != nil {
		panic(err)
	}

	fmt.Println("Part A: ", partA(input))
	fmt.Println("Part B: ", partB(input))
	fmt.Println("Finished: ", time.Since(start))
}

func partA(lines []string) any {
	return "not implemented"
}

func partB(lines []string) any {
	return "not implemented"
}

func parseInput(filename string) ([]string, error) {
	_, thisFile, _, _ := runtime.Caller(0)
	dir := filepath.Dir(thisFile)
	filename = filepath.Join(dir, filename)

	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0)

	s := bufio.NewScanner(f)
	for s.Scan() {
		lines = append(lines, s.Text())
	}

	return lines, nil
}`

const TestTemplate = `// Code generated by aoc; DO NOT EDIT.
package main

import (
	"strings"
	"testing"
)

var testInput = ` + "`" + "`" + `

func TestPartA(t *testing.T) {
	input := parseTestInput()
	exampleAns := 0
	ans := partA(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", ans, exampleAns)
	}
}

func TestPartB(t *testing.T) {
	input := parseTestInput()
	exampleAns := 0
	ans := partB(input)
	if ans != exampleAns {
		t.Errorf("expected: %v, actual: %v", ans, exampleAns)
	}
}

func parseTestInput() []string {
	return strings.Split(testInput, "\n")
}`
